// this file is @generated
import { parseDateTime } from "../datetime.js";
import { extraProperties, pickProperties } from "../json.js";
import { type EventId, EventIdSerializer } from "./eventId.js";
import { type EventType, EventTypeSerializer } from "./eventType.js";
import {
  type SubscriptionEventData,
  SubscriptionEventDataSerializer,
} from "./subscriptionEventData.js";

export interface SubscriptionEvent extends SubscriptionEventData {
  id: EventId;
  timestamp: Date;
  type: EventType;
}

/** Converts `SubscriptionEvent` values from (`parse`) and to (`serialize`) their JSON form. */
export const SubscriptionEventSerializer = {
  parse(json: any): SubscriptionEvent {
    return {
      ...extraProperties(json, [
        "id",
        "timestamp",
        "type",
        "activated_at",
        "auto_advance_invoices",
        "billing_day_anchor",
        "billing_start_date",
        "cancellation_reason",
        "change_type",
        "charge_automatically",
        "created_at",
        "currency",
        "custom_properties",
        "customer_alias",
        "customer_id",
        "customer_name",
        "end_date",
        "invoice_memo",
        "invoice_threshold",
        "mrr_cents",
        "net_terms",
        "period",
        "plan_name",
        "purchase_order",
        "start_date",
        "status",
        "subscription_id",
        "trial_duration",
        "version",
      ]),
      ...pickProperties(SubscriptionEventDataSerializer.parse(json), [
        "activatedAt",
        "autoAdvanceInvoices",
        "billingDayAnchor",
        "billingStartDate",
        "cancellationReason",
        "changeType",
        "chargeAutomatically",
        "createdAt",
        "currency",
        "customProperties",
        "customerAlias",
        "customerId",
        "customerName",
        "endDate",
        "invoiceMemo",
        "invoiceThreshold",
        "mrrCents",
        "netTerms",
        "period",
        "planName",
        "purchaseOrder",
        "startDate",
        "status",
        "subscriptionId",
        "trialDuration",
        "version",
      ]),
      id: EventIdSerializer.parse(json["id"]),
      timestamp: parseDateTime(json["timestamp"]),
      type: EventTypeSerializer.parse(json["type"]),
    };
  },

  serialize(value: SubscriptionEvent): any {
    return {
      ...extraProperties(value, [
        "id",
        "timestamp",
        "type",
        "activatedAt",
        "autoAdvanceInvoices",
        "billingDayAnchor",
        "billingStartDate",
        "cancellationReason",
        "changeType",
        "chargeAutomatically",
        "createdAt",
        "currency",
        "customProperties",
        "customerAlias",
        "customerId",
        "customerName",
        "endDate",
        "invoiceMemo",
        "invoiceThreshold",
        "mrrCents",
        "netTerms",
        "period",
        "planName",
        "purchaseOrder",
        "startDate",
        "status",
        "subscriptionId",
        "trialDuration",
        "version",
      ]),
      ...pickProperties(SubscriptionEventDataSerializer.serialize(value), [
        "activated_at",
        "auto_advance_invoices",
        "billing_day_anchor",
        "billing_start_date",
        "cancellation_reason",
        "change_type",
        "charge_automatically",
        "created_at",
        "currency",
        "custom_properties",
        "customer_alias",
        "customer_id",
        "customer_name",
        "end_date",
        "invoice_memo",
        "invoice_threshold",
        "mrr_cents",
        "net_terms",
        "period",
        "plan_name",
        "purchase_order",
        "start_date",
        "status",
        "subscription_id",
        "trial_duration",
        "version",
      ]),
      id: EventIdSerializer.serialize(value.id),
      timestamp: value.timestamp,
      type: EventTypeSerializer.serialize(value.type),
    };
  },
};
